version: 1.0.{build}

shallow_clone: true

configuration: Release

platform:
- Win32
- x64

environment:
  matrix:
  - VisualStudioVersion: 9.0
    PlatformToolset: v90
  - VisualStudioVersion: 10.0
    PlatformToolset: v100
  - VisualStudioVersion: 11.0
    PlatformToolset: v110_xp
  - VisualStudioVersion: 12.0
    PlatformToolset: v120_xp
  - VisualStudioVersion: 14.0
    PlatformToolset: v140_xp

artifacts:
- path: bin\bmpow*.dll

deploy: off
