version: 1.0.{build}

image: Visual Studio 2015

shallow_clone: true

configuration: Release

platform:
- Win32
- x64

environment:
  VisualStudioVersion: 9.0
  PlatformToolset: v90
  matrix:
  - WIN32_WINNT: 0x0501
    SubSystemVersion: 5.01
  - WIN32_WINNT: 0x0601
    SubSystemVersion: 6.01

before_build:
- msbuild /nologo /preprocess:project_$(configuration)_$(platform).xml

build:
  project: bmpow.vcxproj

test_script:
- python test_pow.py
- cmd: C:\Python27-x64\python test_pow.py

artifacts:
- path: project*.xml
- path: bin\bmpow*.dll

deploy: off
