version: 1.0.{build}

shallow_clone: true

configuration: Release

platform:
- Win32
- x64

environment:
  matrix:
  - VisualStudioVersion: 9.0
  - VisualStudioVersion: 10.0
  - VisualStudioVersion: 11.0
    PlatformToolset: v110_xp
  - VisualStudioVersion: 12.0
    PlatformToolset: v120_xp
  - VisualStudioVersion: 14.0
    PlatformToolset: v140_xp

build_script:
- msbuild "bmpow.vcxproj" /preprocess:"bmpow_%PLATFORM%_%VisualStudioVersion%_pp.vcxproj" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- msbuild "bmpow.vcxproj" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
- path: bmpow_*

deploy: off
