version: 1.0.{build}

shallow_clone: true

environment:
  MSYSTEM: MINGW64

build_script:
- cmd: >-
    C:\msys64\mingw64\bin\gcc -v -Wall -O3 -D_WIN32 -I"C:\msys64\mingw64\include" -o bmpow64_m.o -c bmpow.c

    gcc -v -static-libgcc -shared bmpow64_m.o -D_WIN32 -O3 -I"C:\msys64\mingw64\include" -L"C:\msys64\mingw64\lib" -fPIC -shared -lcrypt32 -leay32 -lwsock32 -o bmpow64_m.dll -Wl,--out-implib,bmpow64_m.a

- cmd: >-
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86

    CL /I C:\OpenSSL-Win32\include /INCREMENTAL bmpow.c /MT /link /DLL /OUT:bmpow32.dll /LIBPATH:"C:\OpenSSL-Win32\lib" libeay32.lib ws2_32.lib

- cmd: >-
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

    CL /I C:\OpenSSL-Win64\include /INCREMENTAL bmpow.c /MT /link /DLL /OUT:bmpow64.dll /LIBPATH:"C:\OpenSSL-Win64\lib" libeay32.lib ws2_32.lib

test_script:
- cmd: >-
    python test_pow.py

    C:\Python27-x64\python test_pow.py

deploy: off
