version: 1.0.{build}

shallow_clone: true

configuration: Release

platform:
#- Win32
- x64

environment:
  VisualStudioVersion: 9.0
  PlatformToolset: v90
  matrix:
  - WIN32_WINNT: 0x0501
    SubSystemVersion: 5.01
#  - WIN32_WINNT: 0x0601
#    SubSystemVersion: 6.01

#test_script:
#- python test_pow.py
#- cmd: C:\Python27-x64\python test_pow.py

artifacts:
- path: project.xml
#- path: bin\bmpow*.dll

deploy: off
