version: 1.0.{build}

shallow_clone: true

configuration: Release

platform:
- Win32
- x64

environment:
  VisualStudioVersion: 9.0
  PlatformToolset: v90
  matrix:
  - PreprocessorDefinitions: _WIN32_WINNT=0x0501
  - PreprocessorDefinitions: _WIN32_WINNT=0x0601

test_script:
- python test_pow.py
- cmd: C:\Python27-x64\python test_pow.py

artifacts:
- path: bin\bmpow*.dll

deploy: off
