version: 1.0.{build}

shallow_clone: true

configuration: Release

platform:
- Win32
- x64

environment:
  VisualStudioVersion: 14.0

build_script:
- msbuild "bmpow.vcxproj" /p:ClCompile.PreprocessToFile=true /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
- cmd: >-
    python test_pow.py

    C:\Python27-x64\python test_pow.py

artifacts:
- path: bin\bmpow*.dll

deploy: off
